CREATE PROCEDURE SP_REGISTRAR_PERSONA(IN NOMBRE VARCHAR(100), IN APEPAT VARCHAR(50), IN APEMAT VARCHAR(50), IN NRODOCUMENTO VARCHAR(11), IN TIPDOCUMENTO VARCHAR(12),IN SEXO VARCHAR(10), IN TELEFONO VARCHAR(12))
BEGIN
DECLARE CANTIDAD INT;
SET @CANTIDAD:=(SELECT COUNT(*) FROM persona WHERE persona_nrodocumento=NRODOCUMENTO);
IF @CANTIDAD=0 THEN
	INSERT INTO persona(persona_nombre,persona_apepat,persona_apemat,persona_nrodocumento,persona_tipodocumento,persona_sexo,persona_telefono,persona_feregistro,persona_estatus)VALUES(NOMBRE,APEPAT,APEMAT,NRODOCUMENTO,TIPDOCUMENTO,SEXO,TELEFONO,CURDATE(),'ACTIVO');
	SELECT 1;
ELSE
	SELECT 2;
END IF;

END